# Generated by Django 3.2.14 on 2022-07-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'verbose_name': 'Tree', 'verbose_name_plural': 'Trees'},
        ),
    ]
