# Generated by Django 3.2.14 on 2022-07-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_alter_tree_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeWorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=1024, verbose_name='plan')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_work_plans', to='tree.tree', verbose_name='tree')),
            ],
            options={
                'verbose_name': 'Tree work plan',
                'verbose_name_plural': 'Tree work plans',
            },
        ),
    ]
