# Generated by Django 3.2.14 on 2022-07-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_treeworkplan_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='location'),
        ),
    ]
